# fly.toml file generated for besties-gpt on 2023-03-28T18:59:09-07:00

app = "besties-gpt"
primary_region = "sjc"

[build]
  [build.args]
    NEXT_PUBLIC_EXAMPLE = "Value goes here"

[env]
  PORT = "8080"
